
default: &default
  adapter: postgresql
  encoding: utf8
  
  
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0
  
development:
  <<: *default
  database: berborak_development

  

test:
  <<: *default
  database: berborak_test


production:
  <<: *default
  database: berborak_production
  username: berborak
  password: <%= ENV['BERBORAK_DATABASE_PASSWORD'] %>
  adapter: postgresql
  database: db/production.pg
 
