
default: &default
  adapter: postgresql
  encoding: unicode
  
  
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0
  
development:
  <<: *default
  database: bolehboleh_development

  

test:
  <<: *default
  database: bolehboleh_test


production:
  <<: *default
  database: bolehboleh_production
  username: bolehboleh
  password: <%= ENV['BOLEHBOLEH_DATABASE_PASSWORD'] %>
  adapter: postgresql
  database: mydatabase
 
